from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageOps


PROJECT_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class BoxAudit:
    source: str
    modality: str
    image_id: str
    image_path: Path
    mask_path: Path
    width: int
    height: int
    bbox: tuple[int, int, int, int] | None
    changed_ratio: float
    bbox_area_ratio: float
    touches_edge: bool
    status: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check whether QGIS mask exports can be converted into YOLO boxes."
    )
    parser.add_argument(
        "--mask-audit-csv",
        type=Path,
        default=PROJECT_ROOT / "data" / "combined" / "mask_export_audit.csv",
        help="CSV generated by audit_mask_exports.py.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=PROJECT_ROOT / "data" / "combined" / "yolo_mask_box_audit.csv",
    )
    parser.add_argument(
        "--preview-dir",
        type=Path,
        default=PROJECT_ROOT / "data" / "combined" / "yolo_mask_previews",
    )
    parser.add_argument(
        "--modality",
        choices=["rgb", "lidar", "both"],
        default="rgb",
        help="Which modality to audit. RGB is recommended for YOLO annotations.",
    )
    parser.add_argument(
        "--include-negatives",
        action="store_true",
        help="Also audit negative samples. By default, only positive site images are checked.",
    )
    parser.add_argument(
        "--detection-method",
        choices=["red", "difference"],
        default="red",
        help="How to detect the QGIS mask. Use red for red polygon outlines.",
    )
    parser.add_argument(
        "--diff-threshold",
        type=int,
        default=30,
        help="Minimum RGB difference used when --detection-method difference is selected.",
    )
    parser.add_argument(
        "--min-bbox-area-ratio",
        type=float,
        default=0.002,
        help="Minimum bounding-box/image area ratio considered usable.",
    )
    parser.add_argument(
        "--max-bbox-area-ratio",
        type=float,
        default=0.85,
        help="Maximum bounding-box/image area ratio considered usable.",
    )
    parser.add_argument(
        "--edge-margin-ratio",
        type=float,
        default=0.01,
        help="Margin ratio used to flag boxes touching image borders.",
    )
    parser.add_argument("--max-previews", type=int, default=60)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = _read_rows(args.mask_audit_csv)
    rows = _filter_rows(rows, args)
    if not rows:
        print("No usable mask rows to audit.")
        return 1

    audits = [_audit_row(row, args) for row in rows]
    args.output_csv.parent.mkdir(parents=True, exist_ok=True)
    args.preview_dir.mkdir(parents=True, exist_ok=True)
    _write_csv(audits, args.output_csv)
    _write_previews(audits, args.preview_dir, args.max_previews)
    _print_summary(audits, args.output_csv, args.preview_dir)
    return 0


def _read_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def _filter_rows(rows: list[dict[str, str]], args: argparse.Namespace) -> list[dict[str, str]]:
    filtered = [row for row in rows if row["status"] == "ok"]
    if args.modality != "both":
        filtered = [row for row in filtered if row["modality"] == args.modality]
    if not args.include_negatives:
        filtered = [row for row in filtered if "_neg" not in row["image_id"]]
    return filtered


def _audit_row(row: dict[str, str], args: argparse.Namespace) -> BoxAudit:
    image_path = Path(row["image_path"])
    mask_path = Path(row["mask_path"])
    with Image.open(image_path).convert("RGB") as clean_image:
        clean = np.asarray(clean_image, dtype=np.int16)
        width, height = clean_image.size
    with Image.open(mask_path).convert("RGB") as mask_image:
        mask = np.asarray(mask_image, dtype=np.int16)

    if args.detection_method == "red":
        changed = _red_mask(mask)
    else:
        difference = np.abs(mask - clean).max(axis=2)
        changed = difference >= args.diff_threshold
    changed_ratio = float(changed.mean())
    bbox = _bbox_from_mask(changed)
    bbox_area_ratio = _bbox_area_ratio(bbox, width, height)
    touches_edge = _touches_edge(bbox, width, height, args.edge_margin_ratio)
    status = _status(bbox, bbox_area_ratio, touches_edge, args)

    return BoxAudit(
        source=row["source"],
        modality=row["modality"],
        image_id=row["image_id"],
        image_path=image_path,
        mask_path=mask_path,
        width=width,
        height=height,
        bbox=bbox,
        changed_ratio=changed_ratio,
        bbox_area_ratio=bbox_area_ratio,
        touches_edge=touches_edge,
        status=status,
    )


def _red_mask(mask: np.ndarray) -> np.ndarray:
    red = mask[:, :, 0]
    green = mask[:, :, 1]
    blue = mask[:, :, 2]
    return (
        (red > 110)
        & (green < 90)
        & (blue < 90)
        & (red > green * 1.6)
        & (red > blue * 1.45)
    )


def _bbox_from_mask(mask: np.ndarray) -> tuple[int, int, int, int] | None:
    ys, xs = np.nonzero(mask)
    if len(xs) == 0 or len(ys) == 0:
        return None
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def _bbox_area_ratio(
    bbox: tuple[int, int, int, int] | None, width: int, height: int
) -> float:
    if bbox is None:
        return 0.0
    x1, y1, x2, y2 = bbox
    return ((x2 - x1) * (y2 - y1)) / float(width * height)


def _touches_edge(
    bbox: tuple[int, int, int, int] | None,
    width: int,
    height: int,
    margin_ratio: float,
) -> bool:
    if bbox is None:
        return False
    x1, y1, x2, y2 = bbox
    margin_x = max(1, int(width * margin_ratio))
    margin_y = max(1, int(height * margin_ratio))
    return (
        x1 <= margin_x
        or y1 <= margin_y
        or x2 >= width - margin_x
        or y2 >= height - margin_y
    )


def _status(
    bbox: tuple[int, int, int, int] | None,
    bbox_area_ratio: float,
    touches_edge: bool,
    args: argparse.Namespace,
) -> str:
    problems = []
    if bbox is None:
        problems.append("no_detected_mask")
    if bbox is not None and bbox_area_ratio < args.min_bbox_area_ratio:
        problems.append("bbox_too_small")
    if bbox is not None and bbox_area_ratio > args.max_bbox_area_ratio:
        problems.append("bbox_too_large")
    if touches_edge:
        problems.append("bbox_touches_edge")
    return "ok" if not problems else ";".join(problems)


def _write_csv(audits: list[BoxAudit], output_path: Path) -> None:
    with output_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(
            file,
            fieldnames=[
                "source",
                "modality",
                "image_id",
                "image_path",
                "mask_path",
                "width",
                "height",
                "bbox_x1",
                "bbox_y1",
                "bbox_x2",
                "bbox_y2",
                "bbox_area_ratio",
                "changed_ratio",
                "touches_edge",
                "status",
            ],
        )
        writer.writeheader()
        for audit in audits:
            bbox = audit.bbox or ("", "", "", "")
            writer.writerow(
                {
                    "source": audit.source,
                    "modality": audit.modality,
                    "image_id": audit.image_id,
                    "image_path": str(audit.image_path),
                    "mask_path": str(audit.mask_path),
                    "width": audit.width,
                    "height": audit.height,
                    "bbox_x1": bbox[0],
                    "bbox_y1": bbox[1],
                    "bbox_x2": bbox[2],
                    "bbox_y2": bbox[3],
                    "bbox_area_ratio": f"{audit.bbox_area_ratio:.6f}",
                    "changed_ratio": f"{audit.changed_ratio:.6f}",
                    "touches_edge": audit.touches_edge,
                    "status": audit.status,
                }
            )


def _write_previews(audits: list[BoxAudit], preview_dir: Path, max_previews: int) -> None:
    problem_audits = [audit for audit in audits if audit.status != "ok"][:max_previews]
    for audit in problem_audits:
        with Image.open(audit.mask_path).convert("RGB") as image:
            preview = ImageOps.contain(image, (420, 420)).copy()
        scale_x = preview.width / audit.width
        scale_y = preview.height / audit.height
        draw = ImageDraw.Draw(preview)
        if audit.bbox is not None:
            x1, y1, x2, y2 = audit.bbox
            draw.rectangle(
                (
                    x1 * scale_x,
                    y1 * scale_y,
                    x2 * scale_x,
                    y2 * scale_y,
                ),
                outline=(255, 0, 0),
                width=4,
            )
        draw.text((8, 8), audit.status, fill=(255, 0, 0))
        preview.save(preview_dir / f"{audit.source}_{audit.modality}_{audit.image_id}.png")


def _print_summary(audits: list[BoxAudit], output_csv: Path, preview_dir: Path) -> None:
    print(f"Masks audited for YOLO boxes: {len(audits)}")
    ok = [audit for audit in audits if audit.status == "ok"]
    print(f"Usable: {len(ok)}")
    print(f"Problematic: {len(audits) - len(ok)}")

    for source in sorted({audit.source for audit in audits}):
        source_audits = [audit for audit in audits if audit.source == source]
        print(
            f"- {source}: "
            f"{sum(audit.status == 'ok' for audit in source_audits)}/{len(source_audits)} ok"
        )

    bad = [audit for audit in audits if audit.status != "ok"]
    print("Problems:")
    for audit in bad[:40]:
        print(
            f"- {audit.source}/{audit.modality}/{audit.image_id}: "
            f"{audit.status}, bbox_area={audit.bbox_area_ratio:.3f}, "
            f"changed={audit.changed_ratio:.3f}"
        )
    if len(bad) > 40:
        print(f"... and {len(bad) - 40} more")

    print(f"CSV report: {output_csv}")
    print(f"Problem previews: {preview_dir}")


if __name__ == "__main__":
    raise SystemExit(main())
