from __future__ import annotations

import argparse
import csv
import shutil
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert usable QGIS mask bounding boxes into YOLO label files."
    )
    parser.add_argument(
        "--box-audit-csv",
        type=Path,
        default=PROJECT_ROOT / "data" / "combined" / "yolo_mask_box_audit_rgb.csv",
        help="CSV generated by audit_yolo_mask_boxes.py.",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=PROJECT_ROOT / "data" / "yolo_sites",
        help="YOLO dataset output root.",
    )
    parser.add_argument(
        "--class-name",
        default="site_archeologique",
        help="YOLO class name.",
    )
    parser.add_argument(
        "--copy-images",
        action="store_true",
        default=True,
        help="Copy clean images into output-root/images/all.",
    )
    parser.add_argument(
        "--include-patch-types",
        nargs="*",
        default=["large", "patch", "tres_large"],
        choices=["large", "patch", "tres_large"],
        help="Positive image types to include.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rows = _read_rows(args.box_audit_csv)
    usable_rows = [
        row
        for row in rows
        if row["status"] == "ok" and _patch_type(row["image_id"]) in args.include_patch_types
    ]

    if not usable_rows:
        print("No usable YOLO boxes found.")
        return 1

    images_dir = args.output_root / "images" / "all"
    labels_dir = args.output_root / "labels" / "all"
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)

    manifest_rows = []
    for row in usable_rows:
        image_path = Path(row["image_path"])
        output_stem = _output_stem(row)
        output_image = images_dir / f"{output_stem}{image_path.suffix.lower()}"
        output_label = labels_dir / f"{output_stem}.txt"

        if args.copy_images:
            shutil.copy2(image_path, output_image)

        yolo_line = _to_yolo_line(row, class_index=0)
        output_label.write_text(yolo_line + "\n", encoding="utf-8")

        manifest_rows.append(
            {
                "output_id": output_stem,
                "source": row["source"],
                "image_id": row["image_id"],
                "patch_type": _patch_type(row["image_id"]),
                "image_path": str(image_path),
                "output_image": str(output_image),
                "output_label": str(output_label),
                "bbox_area_ratio": row["bbox_area_ratio"],
            }
        )

    _write_manifest(manifest_rows, args.output_root / "yolo_manifest.csv")
    _write_data_yaml(args.output_root / "data.yaml", args.class_name)
    _print_summary(manifest_rows, args.output_root)
    return 0


def _read_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def _patch_type(image_id: str) -> str:
    if "tres_large" in image_id:
        return "tres_large"
    if image_id.endswith("_large"):
        return "large"
    if "_patch" in image_id:
        return "patch"
    return "unknown"


def _output_stem(row: dict[str, str]) -> str:
    return f"{row['source']}_{row['image_id']}"


def _to_yolo_line(row: dict[str, str], class_index: int) -> str:
    width = float(row["width"])
    height = float(row["height"])
    x1 = float(row["bbox_x1"])
    y1 = float(row["bbox_y1"])
    x2 = float(row["bbox_x2"])
    y2 = float(row["bbox_y2"])

    x_center = ((x1 + x2) / 2.0) / width
    y_center = ((y1 + y2) / 2.0) / height
    box_width = (x2 - x1) / width
    box_height = (y2 - y1) / height

    return (
        f"{class_index} "
        f"{x_center:.6f} {y_center:.6f} "
        f"{box_width:.6f} {box_height:.6f}"
    )


def _write_manifest(rows: list[dict[str, str]], output_path: Path) -> None:
    fieldnames = [
        "output_id",
        "source",
        "image_id",
        "patch_type",
        "image_path",
        "output_image",
        "output_label",
        "bbox_area_ratio",
    ]
    with output_path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _write_data_yaml(output_path: Path, class_name: str) -> None:
    output_path.write_text(
        "\n".join(
            [
                "path: .",
                "train: images/all",
                "val: images/all",
                "",
                "names:",
                f"  0: {class_name}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _print_summary(rows: list[dict[str, str]], output_root: Path) -> None:
    print(f"YOLO positive samples written: {len(rows)}")
    for patch_type in sorted({row["patch_type"] for row in rows}):
        print(f"- {patch_type}: {sum(row['patch_type'] == patch_type for row in rows)}")
    print(f"Images: {output_root / 'images' / 'all'}")
    print(f"Labels: {output_root / 'labels' / 'all'}")
    print(f"Manifest: {output_root / 'yolo_manifest.csv'}")
    print(f"Data YAML: {output_root / 'data.yaml'}")


if __name__ == "__main__":
    raise SystemExit(main())
